# Generated by Django 4.2.8 on 2023-12-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='plan_status',
            field=models.BooleanField(default=True),
        ),
    ]
